default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, ../sfAdminDashPlugin/css/default.css]

  javascripts:    [jquery.min.js, ../sfAdminDashPlugin/js/sf_admin_dash.js]

  has_layout:     on
  layout:         layout
