default:
  http_metas:
    content-type: text/html

  metas:
    title:        JoyReactor - твое хорошее настроение
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, jquery.rating.css, custom-form-elements.css]

  javascripts:    [/sfProtoculousPlugin/js/prototype.js, excanvas.pack.js, custom-form-elements.js, webtoolkit.aim.js, jquery.min.js, jquery.flot.pack.js, jquery.cookie.js, jquery.rating.js, jquery.timers.js, CtrlEnter.js, TimeZoneOffset.js, jquery.tagcloud-2.js, date.format.js, 1024fix.js, externalLinks.js, commentsHighlight.js]

  has_layout:     on
  layout:         layout
