generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Blog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          blog
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        object_actions:
          merge: ~
          _edit: ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
